import type { Metadata } from "next";
import "../globals.css";
import MainNavbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "YC Directory",
  description: "Generated by create next app",
};

export default function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <MainNavbar />
      {children}
    </main>
  );
}
